services:
  octopus:
    build:
      context: .
    image: octopus-local
    ports:
      - '8080:8080'
    volumes:
      - './data:/app/data'
    container_name: octopus
    restart: unless-stopped
